# -*- coding: latin-1 -*-

from . import lorem_ipsum


WORDS = (
    'A-line',
    'backless',
    'baggy',
    'best',
    'boot-cut',
    'brief',
    'button-down',
    'button-through',
    'casual',
    'clingy',
    'close-fitting',
    'comfortable',
    'conservative',
    'cool',
    'designer',
    'double-breasted',
    'down to',
    'dressy',
    'drip-dry',
    'easy-care',
    'fitting',
    'flame-retardant',
    'formal',
    'full',
    'full-length',
    'hard-wearing',
    'heavy',
    'homespun',
    'hooded',
    'ill-fitting',
    'informal',
    'itchy',
    'Jackie-O',
    'knee-length',
    'light',
    'lined',
    'long',
    'loose',
    'loose-fitting',
    'low',
    'low-cut',
    'machine washable',
    'made-to-measure',
    'modest',
    'monogrammed',
    'non-iron',
    'off-the-peg',
    'off-the-rack',
    'one-piece',
    'open-necked',
    'oversized',
    'padded',
    'peaked',
    'pleated',
    'plunging',
    'polo-neck',
    'preshrunk',
    'prim',
    'prissy',
    'raglan',
    'rainproof',
    'ready-to-wear',
    'revealing',
    'reversible',
    'rolled-up',
    'roomy',
    'ruched',
    'sartorial',
    'scanty',
    'seamed',
    'seamless',
    'sensible',
    'showerproof',
    'single-breasted',
    'skimpy',
    'skin-tight',
    'skinny',
    'sleeveless',
    'slimming',
    'sloppy',
    'smart',
    'snug',
    'sporty',
    'starched',
    'straight',
    'strapless',
    'strappy',
    'stretch',
    'stretchy',
    'tailor-made',
    'tailored',
    'thermal',
    'threadbare',
    'tight',
    'tight-fitting',
    'two-piece',
    'underwired',
    'unfashionable',
    'unlined',
    'V-necked',
    'voluminous',
    'waisted',
    'washable',
    'waterproof',
    'weatherproof',
    'wraparound',
    'zip-up'
)


def paragraphs(*args, **kwargs):
    return lorem_ipsum.paragraphs(*args, words=WORDS, **kwargs)


def words(*args, **kwargs):
    return lorem_ipsum.words(*args, words=WORDS, **kwargs)
