# -*- coding: latin-1 -*-

from . import lorem_ipsum


WORDS = (
    'aalsamic',
    'acerbic',
    'acid',
    'acidic',
    'acorn Squash',
    'acrid',
    'aftertaste',
    'aged',
    'ahi Tuna',
    'aiting',
    'aitter',
    'albacore Tuna',
    'alfalfa',
    'almond',
    'ambrosial',
    'ample',
    'antelope',
    'appealing',
    'appetizing',
    'apple Juice',
    'apples',
    'applesauce',
    'aromatic',
    'artichoke',
    'arugala',
    'asian Noodles',
    'asparagus',
    'astringent',
    'avacado',
    'avocado Roll',
    'babaganoosh',
    'bacon',
    'bagels',
    'baked Beans',
    'baked',
    'barley',
    'bbq',
    'beautiful',
    'beer',
    'bison',
    'bisque',
    'bite-size',
    'bitter',
    'bitter',
    'bivine',
    'black Beans',
    'bland',
    'blazed',
    'blended',
    'bluefish',
    'blunt',
    'boiled',
    'brackish',
    'bread',
    'briny',
    'broccoli',
    'brown',
    'browned',
    'bruscetta',
    'buritto',
    'burnt',
    'buttered',
    'cabbage',
    'cake',
    'caked',
    'calorie',
    'candied',
    'caramelized',
    'carne Asada',
    'carrots',
    'catfish',
    'caustic',
    'celery',
    'center cut',
    'cereal',
    'char-broiled',
    'cheese',
    'cheesy',
    'chicken',
    'chilled',
    'chimichanga',
    'chips',
    'chocolate flavored',
    'chocolate',
    'chocolate',
    'choice',
    'cholesterol free',
    'chowder',
    'chunked',
    'cinnamon',
    'clams',
    'classic',
    'classy',
    'clove  coated',
    'coffee',
    'cold',
    'cookies',
    'cool',
    'copious',
    'corn',
    'country',
    'crab',
    'crafted',
    'creamed',
    'creamy',
    'crisp',
    'crunchy',
    'cupcakes',
    'cured',
    'curry',
    'cutting',
    'dates',
    'dazzling',
    'deep-fried',
    'delectable',
    'delectable',
    'delicious',
    'delight',
    'delightful',
    'delightful',
    'dips',
    'distinctive',
    'donuts',
    'doughy',
    'dressed',
    'dripping',
    'drizzle',
    'drizzled',
    'dry',
    'duck',
    'dulcified',
    'dull',
    'dull',
    'dumplings',
    'edible',
    'edimame',
    'eel Sushi',
    'eggrolls',
    'eggs',
    'elastic',
    'enchilada',
    'encrusted',
    'english Muffins',
    'epicurean taste',
    'ethnic',
    'extraordinary',
    'fajita',
    'falafel',
    'famous',
    'famy',
    'fantastic',
    'fetid',
    'fiery',
    'filet',
    'fish',
    'fizzy',
    'flaky',
    'flat',
    'flavored',
    'flavorful',
    'flavorless',
    'flavorsome',
    'fleshy',
    'fluffy',
    'fondu',
    'fragile',
    'franks',
    'french Dip',
    'french Toast',
    'fresh',
    'fried',
    'frosty',
    'frozen',
    'Fruity',
    'fruity',
    'full',
    'full-bodied',
    'furry',
    'garlic',
    'garlic',
    'garlicky',
    'generous portion',
    'generous',
    'ginger',
    'gingery',
    'gingery',
    'glazed',
    'gnocchi',
    'golden',
    'goose',
    'gorgeous',
    'gourmet',
    'graham Crackers',
    'granola',
    'grapes',
    'greasy',
    'green Beans',
    'grilled',
    'grits',
    'gritty',
    'guancamole',
    'gumbo',
    'Gustatory',
    'haiku Roll',
    'half',
    'halibut',
    'ham',
    'hamburger',
    'Harsh',
    'harsh',
    'harsh',
    'hash Browns',
    'heady',
    'heaping',
    'heart healthy',
    'heart smart',
    'hearty',
    'Heavenly',
    'homemade',
    'Honey',
    'honey',
    'honey-glazed',
    'honeyed',
    'honeyed',
    'hot Dogs',
    'hot',
    'huevos rancheros',
    'hummus',
    'ice Cream',
    'ice-cold',
    'icy',
    'incisive',
    'indian Food',
    'indulgent',
    'infused',
    'insipid',
    'intense',
    'intriguing',
    'irish Stew',
    'italian Bread',
    'jambalaya',
    'jelly / Jam',
    'jerky',
    'juicy',
    'jumbo',
    'kabobs',
    'kale',
    'ketchup',
    'kidney Beans',
    'kingfish',
    'kiwi',
    'kosher',
    'lamb',
    'large',
    'lasagna',
    'lavish',
    'layered',
    'lean',
    'leathery',
    'lemon.',
    'less',
    'light / lite',
    'lightly salted',
    'lightly-breaded',
    'linguine',
    'lip smacking',
    'lively',
    'lobster',
    'low sodium',
    'low',
    'low-fat',
    'lukewarm',
    'luscious',
    'lush',
    'marinated',
    'mashed',
    'meatballs',
    'mellow',
    'mild',
    'milk',
    'milkshake',
    'minty',
    'mixed',
    'mixture of',
    'moist',
    'moist',
    'moose',
    'mouth-watering',
    'nationally famous',
    'natural',
    'nectarous',
    'non-fat',
    'noodles',
    'nutmeg',
    'nutty',
    'oily',
    'open face',
    'organic',
    'ostrich',
    'overpowering',
    'palatable indicates',
    'pancakes',
    'penetrating',
    'pepperoni',
    'peppery',
    'peppery',
    'perfection',
    'petite',
    'pickled',
    'piquant',
    'pizza',
    'plain',
    'pleasant',
    'plump',
    'poached',
    'popular',
    'porter',
    'pounded',
    'prepared',
    'prickly',
    'pulpy',
    'pungent',
    'pureed',
    'quesadilla',
    'quiche',
    'rancid',
    'rank',
    'reduced',
    'refresh',
    'reuben',
    'rich',
    'ripe',
    'roasted',
    'robust',
    'rotten',
    'rubbery',
    'saccharine',
    'saline',
    'salty',
    'saltysavory',
    'Sapid',
    'saporific',
    'saporous',
    'satin',
    'satiny',
    'sauteed',
    'savorless',
    'savory',
    'scrumptious',
    'sea salt',
    'seared',
    'seasoned',
    'sec',
    'served in',
    'served with',
    'sharp',
    'Sharp',
    'sharp',
    'sharp',
    'sharp-tasting',
    'silky',
    'simmered',
    'sizzling',
    'skillfully',
    'small',
    'smelly',
    'smoked',
    'smoky',
    'smooth',
    'smothered',
    'soothing',
    'sour',
    'Southern style',
    'spaghetti',
    'special',
    'spiced',
    'spicy',
    'spinach',
    'spiral-cut',
    'spongy',
    'sprinkled',
    'stale',
    'steamed',
    'steamy',
    'sticky',
    'stinging',
    'strawberry flavored',
    'strong',
    'stuffed',
    'succulent',
    'sugar coated',
    'sugar free',
    'sugared',
    'sugarless.',
    'sugary',
    'superb',
    'sweet',
    'sweet-and-sour',
    'sweetened',
    'syrupy',
    'tangy',
    'tantalizing',
    'tart',
    'Tasteful',
    'tasteful',
    'tasteless',
    'tasty',
    'tater Tots',
    'tender',
    'tepid',
    'terrific',
    'thick',
    'thin',
    'toast',
    'toasted',
    'toothsome',
    'topped',
    'tossed',
    'tough',
    'traditional',
    'treacly',
    'treat',
    'unflavored',
    'unsavory',
    'unseasoned',
    'vanilla flavored',
    'vanilla',
    'velvety',
    'venison',
    'vinegary',
    'waffles',
    'walnuts',
    'warm',
    'waxy',
    'weak',
    'whipped',
    'whole',
    'wine',
    'wonderful',
    'yogurt',
    'yucky!',
    'yummy',
    'zesty',
    'ziti',
    'zucchini'
)


def paragraphs(*args, **kwargs):
    return lorem_ipsum.paragraphs(*args, words=WORDS, **kwargs)


def words(*args, **kwargs):
    return lorem_ipsum.words(*args, words=WORDS, **kwargs)
